version: '3.8'
services:
app:
build: .
ports:
- '4000:4000'
environment:
- PORT=4000
- HF_API_TOKEN=${HF_API_TOKEN}
- REDIS_URL=redis:6379
depends_on:
- redis
redis:
image: redis:7-alpine
restart: unless-stopped